/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Demo */

#ifndef _Included_Demo
#define _Included_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Demo
 * Method:    runApplication
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Demo_runApplication
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
