/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_felixnaumann_reflection_Utils_Native */

#ifndef _Included_me_felixnaumann_reflection_Utils_Native
#define _Included_me_felixnaumann_reflection_Utils_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_felixnaumann_reflection_Utils_Native
 * Method:    isAdministrator
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_me_felixnaumann_reflection_Utils_Native_isAdministrator
  (JNIEnv *, jclass);

/*
 * Class:     me_felixnaumann_reflection_Utils_Native
 * Method:    changeWorkingDirectory
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jint JNICALL Java_me_felixnaumann_reflection_Utils_Native_changeWorkingDirectory
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
